#docker-compose.yml
version: '3.8'

services:
  # service name
  terraria:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - "TZ=Etc/UTC"
      - "TERRARIA_VERSION=1405"
    volumes:
      - "./worlds:/data/Worlds"
      - "./configs:/data/configs/config.txt"
      - "./logs:/data/logs"
      - "./scripts:/data/scripts"
    restart: always