version: '3.8'

services:
  terraria:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - "TZ=Etc/UTC"
      - "TERRARIA_VERSION=1405"
    volumes:
      - "/srv/terraria/data:/data"
    restart: always