#docker-compose.yml
version: '3.8'

services:
  # service name
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      # volume for world files
      - ./world:/terraria/world
      # volume for config file
      - ./config:/terraria/config:ro
    restart: always
